theme: jekyll-theme-minimal
title: Ben Hoskings
description: benjaminhoskings@gmail.com.  </br  >![Book logo](./assets/images/Profile_Pic.png)</br  ><a href="https://www.linkedin.com/in/ben-hoskings" target="_blank">LinkedIn</a>
