theme: jekyll-theme-minimal
title: Ben Hoskings
description: <img src="./docs/assets/images/Profile_Pic.png" alt="drawing" width="200"/> </br  >benjaminhoskings@gmail.com</br  ><a href="https://www.linkedin.com/in/ben-hoskings" target="_blank">LinkedIn</a>
